---
- hosts: local
  become: yes

  pre_tasks:
    - raw: sudo apt-get install -y python3-apt python3-psutil

  roles:
    - { role: install, tags: ['role_install'] }
    - { role: config, tags: ['role_config'] }
