---
- name: Include Task repo.yml
  include: add_repo.yml
  tags: pkgs_install

- name: Include Task latest.yml
  include: url_deb_latest.yml
  tags: pkgs_install

- name: Update Repository
  apt:
    update-cache: yes
  tags: apt_update

- name: Install Packages .deb from URL
  apt:
    deb: "{{ item }}"
    state: present
  loop: "{{ pkgs_urls }}"
  tags: pkgs_install

- name: Install Packages from Repository
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"
  tags: pkgs_install

- name: Check Docker-CE is Installed
  shell: >
    [ "$(dpkg-query -W -f='${db:Status-Abbrev}' docker-ce 2>/dev/null | cut -c1-2)" = "ii" ] ; echo "$?"
  register: docker_is_installed
  tags: docker

- name: Install Docker
  shell: >
    curl -fsSL https://get.docker.com | bash -
  args:
    warn: no
  when: docker_is_installed.stdout != 0
  tags: docker

- name: Install Oh My Zsh!
  shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  become: no
  tags: zsh
  
- name: Change Default SHELL to ZSH
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    shell: /usr/bin/zsh
  tags: zsh

- name: Flatpak | Install Flathub Packages
  flatpak:
    name: "{{ flathub_pkgs }}"
    state: present
    method: system
  tags: flatpak